<?php

namespace ContainerC1T9JMt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_AssetMapper_Assets_Command_Compress_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.asset_mapper.assets.command.compress.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.asset_mapper.assets.command.compress.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('assets:compress', [], 'Pre-compresses files to serve through a web server', false, #[\Closure(name: 'asset_mapper.assets.command.compress', class: 'Symfony\\Component\\AssetMapper\\Command\\CompressAssetsCommand')] fn (): \Symfony\Component\AssetMapper\Command\CompressAssetsCommand => ($container->privates['asset_mapper.assets.command.compress'] ?? $container->load('getAssetMapper_Assets_Command_CompressService')));
    }
}
