<?php

namespace ContainerC1T9JMt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTourPersonnaliseServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TourPersonnaliseService' shared autowired service.
     *
     * @return \App\Service\TourPersonnaliseService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TourPersonnaliseService.php';

        return $container->privates['App\\Service\\TourPersonnaliseService'] = new \App\Service\TourPersonnaliseService(($container->privates['App\\Repository\\TourPersonnaliseRepository'] ?? $container->load('getTourPersonnaliseRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
