<?php

namespace ContainerFCwClvU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReviewServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ReviewService' shared autowired service.
     *
     * @return \App\Service\ReviewService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ReviewService.php';

        return $container->privates['App\\Service\\ReviewService'] = new \App\Service\ReviewService(($container->privates['App\\Repository\\ReviewRepository'] ?? $container->load('getReviewRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
