<?php

namespace ContainerFCwClvU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTourPersonnaliseController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TourPersonnaliseController' shared autowired service.
     *
     * @return \App\Controller\TourPersonnaliseController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'TourPersonnaliseController.php';

        $container->services['App\\Controller\\TourPersonnaliseController'] = $instance = new \App\Controller\TourPersonnaliseController(($container->privates['App\\Service\\TourPersonnaliseService'] ?? $container->load('getTourPersonnaliseServiceService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\TourPersonnaliseController', $container));

        return $instance;
    }
}
