<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC1T9JMt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC1T9JMt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC1T9JMt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC1T9JMt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC1T9JMt\App_KernelDevDebugContainer([
    'container.build_hash' => 'C1T9JMt',
    'container.build_id' => 'e51c823b',
    'container.build_time' => 1764059796,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC1T9JMt');
